### ISSUE TITLE
Video Tutorials on splash screen is wrong video

### ISSUE THREAD

**Issue by shoulders** [joomdev/JD-Builder#10]
On the splash screen just after installing JD Builder (pro) 

![image](https://user-images.githubusercontent.com/319997/68544651-5354f380-03bd-11ea-88ed-0ab3e695e28c.png)

The video tutorials links to https://www.youtube.com/watch?v=oGRjZxAXpao&list=PLv9TlpLcSZTAnfiT0x10HO5GGaTJhUB1K **'How to Use Social Links Element in JD Builder'** which auto plays.

I think the link should go to https://www.youtube.com/playlist?list=PLv9TlpLcSZTAnfiT0x10HO5GGaTJhUB1K **'JD Builder'** channel or perhaps 'Introducing JD Vuiilder - Next Generation Joomla Page Builder'

**Comment by Nishtha003** [comment]
Since we are mentioning it as **Video Tutorial** because of which we are displaying a tutorial video of Social Links element. And page builder is all about elements, that why it's an element tutorial!

Introductory video won't be considered as a tutorial video, I guess!

**Comment by shoulders** [comment]
@Nishtha003 

I am not sure I agree with your logic. Consider: I have just installed JD Builder and I am being offered video tutorials, this should be a link to the videos tutorials not to an individiual topic. Also how does the install splash screen relate to 'Social Links element'? I cant see the link.

> Introductory video won't be considered as a tutorial video, I guess!

Which leaves pointing to the Youtube channel or video tutorial area on your website (if you have one)

**Comment by Nishtha003** [comment]
We added "Social Links" element tutorial there just randomly as an example video tutorial, but as you are suggesting we can now change the link to tutorial playlist, that would be more helpful!

Thanks

**Comment by shoulders** [comment]
Exactly, it makes more sense.

**Comment by chetanmadaan** [comment]
Resolved in internal code base, will be available in the next release.
