### ISSUE TITLE
Admin Menu is shown Twice

### ISSUE THREAD

**Issue by shoulders** [joomdev/JD-Builder#11]
I dont know if this is a Joomla limitation but it is a little annoying. The JD Builder menu is shown twice, once as a standard Joomla component and then a standalone menu. It is not a deal breaker.

![image](https://user-images.githubusercontent.com/319997/68544853-2275be00-03bf-11ea-8e45-6133537829a2.png)

**Comment by chetanmadaan** [comment]
Hi Jon,

It's not a Joomla issue, Adding it after Help is intentional, Just in case you want to be able to quickly get to it without going through the components menu.

Thanks,
Chetan
