### ISSUE TITLE
New Page - save and close button does not show warning when no page title set

### ISSUE THREAD

**Issue by shoulders** [joomdev/JD-Builder#14]
if you download/insert a template (it think this optional) and click save and close without having filled in a page title the warning 'Page Title is required' does not show. It seems 'Save and close' might not have the appropriate javascript event bound.

- The page does not save and close as expect, it is just the warning is not shown.
- The same is the same for 'Save and New'

**Comment by Nishtha003** [comment]
Yup it's there. We'll have to fix it.
@hiteshaggarwal sir

**Comment by chetanmadaan** [comment]
Thanks Jon.

**Comment by Nishtha003** [comment]
Hi Jon,

We have fixed this issue in the latest update of builder v1.3.0 you may please confirm for yourself.

Thanks,
