### ISSUE TITLE
Tag JD Builder Pro where required

### ISSUE THREAD

**Issue by shoulders** [joomdev/JD-Builder#15]
- Within the component you should make a change to show it is pro

![image](https://user-images.githubusercontent.com/319997/68545061-53ef8900-03c1-11ea-9b25-0f53ed9dc575.png)

- Maybe on the installer splash screen so the user know he has installed the pro verion and not the free one again.
- tag the pro in the following list
![image](https://user-images.githubusercontent.com/319997/68545117-d8420c00-03c1-11ea-9462-0b3988d4ad30.png)

**Comment by chetanmadaan** [comment]
Agreed, The footer and the system plugin should both change name.

@chandanndeep & @hiteshaggarwal to make the fix.

**Comment by chandanndeep** [comment]
@shoulders 

We have added the tag in v1.4.0.

![image](https://user-images.githubusercontent.com/17069784/71638511-dee55500-2c87-11ea-9cba-29f65b099bd4.png)
![image](https://user-images.githubusercontent.com/17069784/71638514-f91f3300-2c87-11ea-8ff3-59c50d77c70e.png)

**Comment by shoulders** [comment]
@chandanndeep Does this issue need closing? it seems complete.

**Comment by chandanndeep** [comment]
@shoulders 
Yes, it is complete

**Comment by chandanndeep** [comment]
@shoulders 
Thanks for reporting this
