### ISSUE TITLE
Pro update URL

### ISSUE THREAD

**Issue by shoulders** [joomdev/JD-Builder#16]
I dont know if this is an issue or intentional (i.e. shared code base), the pro version has the same update URL as the free version. The free version 1.2.0  and pro version 1.2.0 have different file compositions.

https://cdn.joomdev.com/updates/jd_builder.xml

This could cause the pro version to be replaced by the free version unless you have a hidden mechanism i dont know about or you intend to share the codebase.

**Comment by chetanmadaan** [comment]
This is indeed no correct.

@chandanndeep to fix.

Thanks,
Chetan

**Comment by chandanndeep** [comment]
@shoulders 

We have updated this in v1.2.1. Sorry, Forget to answer here.

https://www.joomdev.com/my-downloads/jd-builder-pro

**Comment by shoulders** [comment]
no worries, it happens. :smile:
