### ISSUE TITLE
jd seatle 

### ISSUE THREAD

**Issue by sixtus13** [joomdev/JD-Builder#17]
hi
i just downloaded the jd seatle template and i can access the backend page amdinistrator

but the front page is not working and gives an error
This page isn’t working

www.globelaneexpress.com is currently unable to handle this request.
HTTP ERROR 500

whats the problem ?

**Comment by chandanndeep** [comment]
Hello,

500 Error is a Server side error. Please check the link.
https://www.westhost.com/knowledgebase/display/WES/What+Is+A+500+error

and shared link is not a Joomla site link.

**Comment by sixtus13** [comment]
hello sir

**Comment by sixtus13** [comment]
please how can i get rid of the problems?

**Comment by chandanndeep** [comment]
Hello,

Sorry for late reply. You have to talk with you server provider. This is not a template issue.

Thanks,
Chandan
