### ISSUE TITLE
Custom CSS broken after 1.3.0 Update

### ISSUE THREAD

**Issue by FaySmash** [joomdev/JD-Builder#18]
**The Issue:**

Define some custom CSS for any Module:
![modulesettings](https://user-images.githubusercontent.com/30392780/70091640-dbc15f80-161c-11ea-9c6a-e128371801d8.JPG)

---

Expectation: the custom CSS gets applied onto the DOM-element (as in pre 1.3.0)

---

Reality: no custom CSS is applied. It's also shown by a DOM-Inspector:

![elementattributes](https://user-images.githubusercontent.com/30392780/70091647-e0861380-161c-11ea-85c6-70b830410f1f.JPG)

**Comment by chandanndeep** [comment]
First, you have to create the **self** named selector then do the declaration. See the example below.

```
self {
	height:100%;
}
```

**Comment by chandanndeep** [comment]
here is the documentation link.

https://docs.joomdev.com/article/jd-builder-custom-css/

**Comment by FaySmash** [comment]
When I started to work with JDBuilder, this Documentation wasn't available yet. Sucks, that I have to go trough all my Pages and check/edit my custom CSS. Once edited, it works tho.

**Comment by chetanmadaan** [comment]
@FaySmash It kind of changed in this version so, even though documentation didn't existed you still have to re-do some of it.

However, it won't be changing in the future, you are good.
