### ISSUE TITLE
Custom CSS in Page Settings isn't working

### ISSUE THREAD

**Issue by FaySmash** [joomdev/JD-Builder#19]
**The Issue:**

Open a Page. Go to Options -> Page Options -> Settings -> Advanced -> Custom Code and enter Custom Code:
![Custom CSS](https://user-images.githubusercontent.com/30392780/71367417-48d56e80-25a5-11ea-94a9-14d7201bbad9.PNG)

---

Expectation: the custom CSS gets applied onto the DOM-element

---

Reality: no custom CSS is applied. It's also shown by a DOM-Inspector:

![Issue](https://user-images.githubusercontent.com/30392780/71367469-702c3b80-25a5-11ea-9d06-6753ca79977e.PNG)

**Comment by chandanndeep** [comment]
Hello @FaySmash ,

In Custom code tab. There are three boxes for custom code. For CSS you have to save your code in second box whose language is missing.

![image](https://user-images.githubusercontent.com/17069784/71393038-8f23df80-2630-11ea-9f21-bbddd4a82576.png)


Thanks,
Chandan

**Comment by FaySmash** [comment]
This works, thanks. It's a little confusing tho

**Comment by chandanndeep** [comment]
@FaySmash 
Yeah, that was a mistake. Which we fixed in Dev Branch.
