### ISSUE TITLE
Import current pages

### ISSUE THREAD

**Issue by jaydenrussell** [joomdev/JD-Builder#2]
Most sites are already customized and not being able to import the layout makes it a hard sell to use.

**Comment by chetanmadaan** [comment]
I agree. We do have plans in the near future to provide some sort of migration path from other Joomla builders and core Joomla content as well.
-- Chetan

**Comment by Joomill** [comment]
It would also be nice when pages (build with JD Builder) can be exported and imported in other sites. 
Or when you can add custom pages/blocks to the library

**Comment by chetanmadaan** [comment]
Thanks Jeroen, That's a great idea. The second one is something we didn't had on our radar.

We'll be getting these implemented in the upcoming releases.

**Comment by shoulders** [comment]
I would also like to import and export pages from page builder.

**Scenario**

I already have a site with content but I want to migrate to JD seattle and use some of the JD Builder pages (not all) from the JD Seattle quickstart package. I was expecting to be able to setup the quickstart website and export the pages I wanted and then import into my current website without have to start again (i.e. manually installing JDseattle template and JD Page Builder).

This also allows you to develop pages offline on your local dev site and then upload them to your live site when they are ready.

Thanks

**Comment by chetanmadaan** [comment]
Hi Jon,

In the Newer version of JD builder (_which will be coming up within next 2-3 weeks_), it already has the functionality regarding exporting and importing pages.

I'll post back here once a release is done.

Thanks,
Chetan

**Comment by Nishtha003** [comment]
Import & Export was added!
