### ISSUE TITLE
[Feature Request] Add the ability to edit the alt-Attribute of Images

### ISSUE THREAD

**Issue by FaySmash** [joomdev/JD-Builder#20]
The only text attribute you can add to an image is the Title:
![jdb](https://user-images.githubusercontent.com/30392780/73778349-5dec1280-478b-11ea-9282-93a0011a5da7.JPG)

This results in the `title` and `alt` attribute being set:
![console](https://user-images.githubusercontent.com/30392780/73778498-9e4b9080-478b-11ea-8761-650b02ea8de9.JPG)

---
I don't want to add a title tough only the `alt` Attribute like this:
![console](https://user-images.githubusercontent.com/30392780/73778657-d6eb6a00-478b-11ea-889e-3e411e9d1e3a.JPG)

Could you please and an option like this?:
![jdb](https://user-images.githubusercontent.com/30392780/73778883-2b8ee500-478c-11ea-802e-03dec42434fb.JPG)

**Comment by chetanmadaan** [comment]
Hello and Thank you for the feature request. It's always great to know our products are being used by the Joomla community.

@hiteshaggarwal, could you please have a look at this when you get a minute?

**Comment by hiteshaggarwal** [comment]
Hi, This is fixed for image element. You can download a copy from branch https://github.com/joomdev/JD-Builder/tree/dev-1.4.0

changes are https://github.com/joomdev/JD-Builder/commit/678cb863f346799fe10b5f6cb57c68a37812ec40 and https://github.com/joomdev/JD-Builder/commit/8e6a7c60c0436da13912a630a48212b9b60e07cd

Thanks

**Comment by FaySmash** [comment]
Hi, sorry for the late reply. Just tested the dev release and it works as intended. But now, there is no possibility to change the title-Attribute of the image. Personally, I don't need the title-Attribute, just the alt one but the most satisfyingly solution would be to add a Field to change the alt-Attribute besides the field to change the title-Attribute, like it's shown in my previous comment.

**Comment by hiteshaggarwal** [comment]
Hi, We separate the title and alt option for image. Thanks for suggestion. Will update the code in our next release.

**Comment by chandanndeep** [comment]
@FaySmash 

New version (v1.6.1) has been released.

**Comment by FaySmash** [comment]
@chandanndeep works like a charm, thanks!

**Comment by chandanndeep** [comment]
@FaySmash 

Great.
