### ISSUE TITLE
[Bug] No space between id and class attributes

### ISSUE THREAD

**Issue by FaySmash** [joomdev/JD-Builder#21]
**The Issue:**

No space is added between generated `id` and `class` attributes

---

Expectation: a white space should be presen't between the `id`  and `class` attribute:
`id="jdc-fi00013605490449oz" class="jdb-column jdb-col-lg-2 jdc-fi00013605490449oz"`

---

Reality: no space is inserted between those attributes, causing trouble with some joomla plugins:
`id="jdc-fi00013605490449oz"class="jdb-column jdb-col-lg-2 jdc-fi00013605490449oz"`

**Comment by chetanmadaan** [comment]
@FaySmash Are you positive you are running the latest version? I quickly checked our demo page and I can see the white space is there.
https://try.joomdev.com/jd-builder/index.php

![image](https://user-images.githubusercontent.com/3968575/76336731-cd927780-62cc-11ea-8865-dd7cdba9d461.png)

**Comment by FaySmash** [comment]
In fact, I do not. The update notification appeared one day later in my joomla instance, I didn't came around to install it yet, I'll do it asap and report back.

**Comment by FaySmash** [comment]
The issue was fixed by updating to release 1.5.0
