### ISSUE TITLE
refreshJDLightbox is not defined

### ISSUE THREAD

**Issue by FaySmash** [joomdev/JD-Builder#25]
Since I updated to JD Builder 1.6.0, I get dozens of this Error Messages in the Console:
![error](https://user-images.githubusercontent.com/30392780/81724733-2923e180-9485-11ea-9b73-57fcb774c60c.JPG)

Those Messages are caused by this HTML, which appears in every DOM Element with the `jdb-image` Class:

```
<script>
      refreshJDLightbox();
   </script>
```

**Comment by chetanmadaan** [comment]
This is probably because of the newer version. If you open the page you are having issued on and save it again. It should go away. Make sure you are running 1.6.1

**Comment by FaySmash** [comment]
I opened the Page in JD Builder, changed something and saved. The issue still persists tho. I'm running 1.6.1 (which appears to be the same than 1.6.0 according to github?)

**Comment by chetanmadaan** [comment]
The problem is with the image elements. Can you try opening the individual image element and saving it and see if that fixes the issue?

**Comment by FaySmash** [comment]
I created a new Page and added an Image Element, the Problem still appears. I exported the Page and attached it.
[jdb-test-layout27-13May20.json.txt](https://github.com/joomdev/JD-Builder/files/4620087/jdb-test-layout27-13May20.json.txt)

**Comment by chetanmadaan** [comment]
Thanks. I'll run some test here.

**Comment by FaySmash** [comment]
Fixed in 1.7.0
