### ISSUE TITLE
I have a new feature request for JD-Builder

### ISSUE THREAD

**Issue by ConfidantCommunications** [joomdev/JD-Builder#27]
On controls with sliders—let the user enter a number directly. It's too hard to get the exact number usually.

**Comment by chetanmadaan** [comment]
What/where? screenshot?

**Comment by ConfidantCommunications** [comment]
For example, in the gradient editor for backgrounds. 
![Screen Shot 2020-06-12 at 3 44 06 PM](https://user-images.githubusercontent.com/1410814/84548771-aa100c00-acc3-11ea-897f-8c03a3786d9f.png)

**Comment by chetanmadaan** [comment]
True. We need this on the gradient and box shadow input field as well where the user can directly input the desired css.

**Comment by Nishtha003** [comment]
Made this change for Box Shadow will do it for Gradient as well!

**Comment by ConfidantCommunications** [comment]
Great, thanks.
