### ISSUE TITLE
 Class 'FieldsHelper' not found 

### ISSUE THREAD

**Issue by Joomill** [joomdev/JD-Builder#3]
When System Fields plugin is disabled i got the message "Class 'FieldsHelper' not found"
I don't think it's mandatory to have this plugin active

**Comment by chetanmadaan** [comment]
Yes, we had another user report this too and are working on a fix, should be in the next release.

**Comment by chetanmadaan** [comment]
Hi Jeroen, this is fixed in v1.1.0 released earlier today.

https://github.com/joomdev/JD-Builder/releases/tag/v1.1.0
