### ISSUE TITLE
Update message error

### ISSUE THREAD

**Issue by ConfidantCommunications** [joomdev/JD-Builder#32]
When I visit the JD Builder page list it says in red: “You are using outdated version of JD Builder v1.11.2. Please update to the latest version 1.11.2”. Obviously I am using the current version. Also, clicking the link takes me to to a 404 error on GitHub.

**Comment by Nishtha003** [comment]
Hi,

It's a known issue, you can ignore it if you have already updated your JD Builder to v1.11.2.

The message will be removed in the upcoming release.

Thanks,
Nishtha

**Comment by Nishtha003** [comment]
This has been removed in JD Builder v1.11.3

Topic closed.
