### ISSUE TITLE
Constant crashing in Firefox for Mac

### ISSUE THREAD

**Issue by ConfidantCommunications** [joomdev/JD-Builder#33]
Not sure what changed but JD Builder 1.11.3 refuses to run on Mac Firefox 78.9.0esr (64-bit). As soon as I summon an edit window for a module or a page, it hard crashes the browser tab. I can't even get at the console log. Joomla version 3.9.25. Chrome runs fine.

**Comment by ConfidantCommunications** [comment]
I discovered that restarting the browser did not help, but restarting the machine fixed it.

**Comment by chetanmadaan** [comment]
Glad it's resolved.
