### ISSUE TITLE
post install splash screen - changelog link does not work

### ISSUE THREAD

**Issue by shoulders** [joomdev/JD-Builder#7]
on the following screen when you click on the changelog link it takes you to the product page for JD builder (https://www.joomdev.com/jd-builder) and not the changelog.

I think you need to add an Anchor tag to this url so it scrolls to the bottom of this page where the changelog is

![pagebuilder changelog](https://user-images.githubusercontent.com/319997/66049387-39ed9b80-e523-11e9-9f4f-e4a2ef431cd3.JPG)

**Comment by chetanmadaan** [comment]
The link has been changed in the internal repo Jon and should be release in the next release.

https://www.joomdev.com/jd-builder#changelog

Thanks for pointing out.
